name: Build

on:
  push:
    branches: ["*"]
    tags: ["*"]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run build
        run: pnpm build --mode product
      - name: Publish to NPM
        if: startsWith(github.ref, 'refs/tags/v')
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
